-- CreateTable
CREATE TABLE `Article` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `metaKeyword` VARCHAR(191) NULL,
    `metaDescription` VARCHAR(191) NULL,
    `body` VARCHAR(191) NOT NULL,
    `imageUrl` VARCHAR(191) NULL,
    `category` ENUM('TRENDS_FASHION', 'TYPES_JEWELLERY', 'OCCASIONS_EVENTS', 'BUYING_GUIDES_REVIEWS', 'HISTORY_CULTURE', 'CARE_MAINTENANCE') NOT NULL,
    `contentType` ENUM('ARTICLE', 'NEWS') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `Article_slug_key`(`slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
