/*
  Warnings:

  - The values [TRENDS_FASHION,TYPES_JEWELLERY,OCCASIONS_EVENTS,BUYING_GUIDES_REVIEWS,HISTORY_CULTURE,CARE_MAINTENANCE] on the enum `Article_category` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `article` MODIFY `category` ENUM('GENERAL_HEALTH', 'DISEASES_CONDITIONS', 'MEDICINES_PHARMA', 'LAB_TESTS', 'SURGICAL_PROCEDURES', 'MENTAL_HEALTH', 'NUTRITION_DIET', 'FITNESS_EXERCISE', 'HEALTHCARE_TECHNOLOGY', 'AYURVEDA_HERBAL', 'SKIN_HAIR_CARE', 'MOTHER_CHILD_HEALTH') NOT NULL;
